language: node_js
node_js:
  - 7

script:
  - npm run lint
  - npm run test:ci
  - npm run build
  -

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'
cache:
  yarn: true
  directories:
    - node_modules